#ifndef NEXTKEY_SDK_H
#define NEXTKEY_SDK_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Generated with cbindgen:0.27.0 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define NEXTKEY_OK 0

#define NEXTKEY_ERR_INVALID_PARAM -1

#define NEXTKEY_ERR_NETWORK -2

#define NEXTKEY_ERR_AUTH -401

#define NEXTKEY_ERR_DECRYPT -3

#define NEXTKEY_ERR_UNKNOWN -999

typedef struct NextKeyClient NextKeyClient;

/*
 卡密信息结构体（C ABI）
 */
typedef struct NextKeyCardInfo {
    uint64_t id;
    char *card_key;
    int32_t activated;
    int64_t duration;
    char *custom_data;
} NextKeyCardInfo;

/*
 创建NextKey客户端（默认AES-256-GCM）
 */
struct NextKeyClient *nextkey_client_new(const char *server_url,
                                         const char *project_uuid,
                                         const char *aes_key);

/*
 创建NextKey客户端（指定加密方案）
 */
struct NextKeyClient *nextkey_client_new_with_scheme(const char *server_url,
                                                     const char *project_uuid,
                                                     const char *aes_key,
                                                     const char *scheme);

/*
 释放客户端
 */
void nextkey_client_free(struct NextKeyClient *client);

/*
 登录
 */
int32_t nextkey_login(struct NextKeyClient *client,
                      const char *card_key,
                      const char *hwid,
                      const char *ip,
                      char **token_out,
                      char **expire_at_out,
                      struct NextKeyCardInfo *card_info_out);

/*
 心跳
 */
int32_t nextkey_heartbeat(struct NextKeyClient *client);

/*
 获取云变量
 */
int32_t nextkey_get_cloud_var(struct NextKeyClient *client, const char *key, char **value_out);

/*
 更新专属信息
 */
int32_t nextkey_update_custom_data(struct NextKeyClient *client, const char *custom_data);

/*
 获取项目信息
 */
int32_t nextkey_get_project_info(struct NextKeyClient *client,
                                 char **uuid_out,
                                 char **name_out,
                                 char **version_out,
                                 char **update_url_out);

/*
 解绑HWID
 */
int32_t nextkey_unbind_hwid(struct NextKeyClient *client, const char *card_key, const char *hwid);

/*
 获取最后的错误消息
 */
const char *nextkey_get_last_error(void);

/*
 释放由库分配的C字符串
 */
void nextkey_free_string(char *s);

/*
 释放卡密信息结构体
 */
void nextkey_free_card_info(struct NextKeyCardInfo *card_info);

#ifdef __cplusplus
}
#endif

#endif // NEXTKEY_SDK_H
