[target.aarch64-linux-android]
linker = "E:/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android21-clang.cmd"
ar = "E:/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"

[build]
target-dir = "target"

[env]
CC_aarch64-linux-android = "E:/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android21-clang.cmd"
CXX_aarch64-linux-android = "E:/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android21-clang++.cmd"
AR_aarch64-linux-android = "E:/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
