[target.aarch64-linux-android]
linker = "/data/data/com.termux/files/home/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-aarch64/bin/aarch64-linux-android21-clang"
ar = "/data/data/com.termux/files/home/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-aarch64/bin/llvm-ar"

[build]
target-dir = "target"

[env]
CC_aarch64-linux-android = "/data/data/com.termux/files/home/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-aarch64/bin/aarch64-linux-android21-clang"
CXX_aarch64-linux-android = "/data/data/com.termux/files/home/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-aarch64/bin/aarch64-linux-android21-clang++"
AR_aarch64-linux-android = "/data/data/com.termux/files/home/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-aarch64/bin/llvm-ar"
