version: 2

project_name: nextkey

dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: nextkey
    main: ./backend/cmd
    binary: nextkey
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - android
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: android
        goarch: amd64
    env:
      - CGO_ENABLED=0

archives:
  - id: nextkey
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      # config.yaml 包含敏感信息，不打包

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: HYB-0225
    name: nextkey
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: '✨ 新功能'
      regexp: '^feat:'
      order: 0
    - title: '🐛 Bug修复'
      regexp: '^fix:'
      order: 1
    - title: '📝 文档'
      regexp: '^docs:'
      order: 2
    - title: '🔧 其他'
      order: 999